# basic options
title: Getting Started with DDF
author: GitHub User
email: wmkellett@gmail.com
description: 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker

plugins_dir:
  - jekyll-sitemap
