# basic options
title: Cleo Integration Cloud
author: GitHub User
email: wmkellett@gmail.com
description: 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-slate

plugins_dir:
  - jekyll-sitemap
